"""Central registry for all Google Docs MCP tools."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from google_docs_mcp_server.tools import (
    advanced_tools,
    docs_tools,
    extraction_tools,
    formatting_tools,
    insertion_tools,
)

TOOL_FUNCTIONS: tuple[Callable[..., Any], ...] = (
    docs_tools.create_doc,
    docs_tools.delete_doc,
    docs_tools.restore_doc,
    docs_tools.rename_doc,
    docs_tools.copy_doc,
    docs_tools.list_recent_docs,
    docs_tools.search_docs,
    docs_tools.get_doc_metadata,
    docs_tools.move_to_folder,
    docs_tools.add_to_folder,
    docs_tools.remove_from_folder,
    docs_tools.create_folder,
    docs_tools.list_folders,
    docs_tools.list_folder_contents,
    docs_tools.export_doc,
    docs_tools.export_to_pdf,
    docs_tools.share_doc,
    docs_tools.unshare_doc,
    docs_tools.list_permissions,
    docs_tools.update_permission,
    docs_tools.list_revisions,
    docs_tools.read_full_doc,
    docs_tools.append_text,
    docs_tools.prepend_text,
    docs_tools.replace_document_content,
    docs_tools.get_document_end_index,
    docs_tools.find_and_replace,
    insertion_tools.insert_text,
    insertion_tools.insert_page_break,
    insertion_tools.insert_footnote,
    insertion_tools.create_bullet_list,
    insertion_tools.create_numbered_list,
    insertion_tools.insert_table,
    insertion_tools.write_table_cell,
    insertion_tools.insert_external_image,
    insertion_tools.batch_updates,
    formatting_tools.format_bold,
    formatting_tools.format_italic,
    formatting_tools.format_underline,
    formatting_tools.format_strikethrough,
    formatting_tools.format_subscript,
    formatting_tools.format_superscript,
    formatting_tools.change_font_family,
    formatting_tools.change_font_size,
    formatting_tools.change_text_color,
    formatting_tools.highlight_text,
    formatting_tools.apply_heading_style,
    formatting_tools.set_paragraph_alignment,
    formatting_tools.indent_paragraph,
    formatting_tools.set_line_spacing,
    formatting_tools.set_paragraph_spacing,
    formatting_tools.set_keep_with_next,
    formatting_tools.set_paragraph_direction,
    formatting_tools.clear_formatting,
    formatting_tools.delete_text,
    formatting_tools.delete_table_row,
    formatting_tools.clear_document,
    formatting_tools.undo_last_action,
    extraction_tools.read_selection,
    extraction_tools.read_page,
    extraction_tools.find_text,
    extraction_tools.get_headers,
    extraction_tools.get_footnotes,
    extraction_tools.read_table_data,
    extraction_tools.read_links,
    extraction_tools.create_comment,
    extraction_tools.reply_to_comment,
    extraction_tools.list_active_comments,
    extraction_tools.list_all_comments,
    extraction_tools.update_comment,
    extraction_tools.delete_comment,
    extraction_tools.update_reply,
    extraction_tools.delete_reply,
    extraction_tools.resolve_comment,
    extraction_tools.insert_linked_bookmark,
    advanced_tools.add_link,
    advanced_tools.remove_link,
    advanced_tools.remove_bullets,
    advanced_tools.insert_table_row,
    advanced_tools.insert_table_column,
    advanced_tools.delete_table_column,
    advanced_tools.merge_table_cells,
    advanced_tools.unmerge_table_cells,
    advanced_tools.replace_image,
    advanced_tools.create_header,
    advanced_tools.create_footer,
    advanced_tools.delete_header,
    advanced_tools.delete_footer,
    advanced_tools.insert_section_break,
    advanced_tools.set_page_setup,
    advanced_tools.list_named_ranges,
    advanced_tools.delete_named_range,
    advanced_tools.replace_named_range_content,
    advanced_tools.get_document_structure,
    advanced_tools.list_images,
    advanced_tools.list_tabs,
    advanced_tools.read_tab,
    advanced_tools.add_tab,
    advanced_tools.rename_tab,
    advanced_tools.delete_tab,
)


def register_all_tools(mcp) -> None:
    for function in TOOL_FUNCTIONS:
        mcp.add_tool(function)
